mv LM007_trim_merged.genes.results ExcNeur_Rep1.merged.genes.results
mv LM008_trim_merged.genes.results ExcNeur_Rep2.merged.genes.results
mv LMA01_trim_merged.genes.results MG_Day2_Rep1.merged.genes.results
mv LMA02_trim_merged.genes.results MG_Day2_Rep2.merged.genes.results
mv LMA03_trim_merged.genes.results MG_Day7_Rep1.merged.genes.results
mv LMA04_trim_merged.genes.results MG_Day7_Rep2.merged.genes.results
mv LMA05_trim_merged.genes.results MG_Day14_Rep1.merged.genes.results
mv LMA06_trim_merged.genes.results MG_Day14_Rep2.merged.genes.results
mv LMA07_trim_merged.genes.results MG_Day30_Rep1.merged.genes.results
mv LMA08_trim_merged.genes.results MG_Day30_Rep2.merged.genes.results
mv LM124_trim_merged.genes.results iPSCs_Rep1.merged.genes.results
mv LM134_trim_merged.genes.results iPSCs_Rep2.merged.genes.results
mv Human1_RNA_Mock_24h_merged.genes.results Macrophage_Rep1.merged.genes.results
mv Human3_RNA_Mock_24h_merged.genes.results Macrophage_Rep2.merged.genes.results
mv MDM-RNAseq-Mock-06h-r3_merged.genes.results Monocyte_Rep1.merged.genes.results
mv MDM-RNAseq-Mock-06h-r4_merged.genes.results Monocyte_Rep2.merged.genes.results
mv SRR5955148_trim_merged.genes.results Microglia_ExVivo_Rep1.merged.genes.results
mv SRR5955157_trim_merged.genes.results Microglia_ExVivo_Rep2.merged.genes.results
mv SRR5955169_trim_merged.genes.results Microglia_ExVivo_Rep3.merged.genes.results
mv SRR5955149_trim_merged.genes.results Microglia_InVitro_Rep1.merged.genes.results
mv SRR5955158_trim_merged.genes.results Microglia_InVitro_Rep2.merged.genes.results